var kultorg = [
    {
        'id': 0,
        'type': 'list',
        'content': [
            {
                'id': 1,
                'content': 'Želim delovati sam/-a',
                'subtitle': 'Bla bla bla la bla bla la bla bla la bla bla'
            }, {
                'id': 2,
                'content': 'Želim se organizirati v skupini',
                'subtitle': 'Bla bla bla la bla bla la bla bla la bla bla'
            }
        ]
    }, {
        'id': 1,
        'type': 'instructions',
        'content': [
            '<div class="htmlcontainer">',
                '<div class="visible-xs centermycontentvertically nazajcontainer"><div class="centermevertically nazaj bck">Nazaj</div></div>',
                '<p>Vse kaže, da je STATUS SAMOZAPOSLENEGA V KULTURI tista oblika delovanja, ki je zate najbolj primerna. Samozaposleni v kulturi so ustvarjalci na področju kulture, ki opravljajo samostojno specializiran poklic s področja kulture kot edini ali glavni poklic.</p>',
                '<h3>Kakšne so prednosti in slabosti statusa?</h3>',
                '<div class="tabs">',
                    '<div class="tab tab-prednosti open">prednosti</div>',
                    '<div class="tab tab-slabosti">slabosti</div>',
                '</div>',
                '<div class="content">',
                    '<div class="open">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list1" name="list1" type="checkbox"><label for="list1"><p>prispevke za socialno varnost plačuje država (če ustrezate <a href="#">pogojem</a> za pridobitev te pravice)</p></label></li>',
                                '<li><input id="list2" name="list2" type="checkbox"><label for="list2"><p>posamezniki/-ce delujejo kot samostojni/-e podjetniki/-ce brez težav, ki jih prinaša status s.p.</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                    '<div class="">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list3" name="list3" type="checkbox"><label for="list3"><p>pravico do plačila prispevkov za socialno varnost je potrebno obnavljati na tri leta</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                '</div>',
                '<h3>Pogoji za pridobitev statusa samozaposlenega v kulturi:</h3>',
                '<div class="tabs">',
                    '<div class="tab tab-prednosti open">za diplomante</div>',
                    '<div class="tab tab-slabosti">za delovno izkušene</div>',
                '</div>',
                '<div class="content">',
                    '<div class="open">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list4" name="list4" type="checkbox"><label for="list4"><p>študijski dosežki morajo obetati pomembno delovanje na področju kulture oz. gre za poklic deficitarne narave (torej npr. če si kipar in primanjkuje kiparjev)</p></label></li>',
                                '<li><input id="list5" name="list5" type="checkbox"><label for="list5"><p>od zaključka študija ali strokovnega izpita (če je ta predpisan) nista minili več kot dve leti</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                    '<div class="">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list6" name="list6" type="checkbox"><label for="list6"><p>samostojno opravljanje specializiranega poklica (če samostojno opravljate umetniško ali drugo dejavnost) na naslednjih področjih: vse oblike ustvarjanja, posredovanja in varovanja kulturnih dobrin na področju nepremične in premične kulturne dediščine, besednih, uprizoritvenih, glasbenih, vizualnih, filmskih, avdiovizualnih in drugih umetnosti ter novih medijev, na področju založništva in knjižničarstva, kinematografije in na drugih področjih kulture. Podroben seznam poklicev, upravičenih do statusa, najdete tukaj. Minister za kulturo odloča, ali gre za kulturno dejavnost v primerih, ko o tem obstaja dvom.</p></label></li>',
                                '<li><input id="list7" name="list7" type="checkbox"><label for="list7"><p>ustrezna izobrazba oz. da  s svojim dosedanjim delom izkazujete, da ste usposobljeni za opravljanje te dejavnosti (npr. video ustvarjalec brez ustrezne izobrazbe mora predložiti svoje dosedanje delo, ki izkazuje, da je upravičen do tega statusa).</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                '</div>',
                '<h3 class="nasveti">Vsi potrebni obrazci in seznam specializiranih poklicev v kulturi</h3>',
                '<form class="ac-custom" autocomplete="off">',
                    '<ul>',
                        '<li><input id="list8" name="list8" type="checkbox"><label for="list8"><p><a href="#">seznam specializiranih poklicev na področju kulture</a></p></label></li>',
                        '<li><input id="list9" name="list9" type="checkbox"><label for="list9"><p><a href="#">vloga za vpis v razvid samozaposlenih v kulturi</a></p></label></li>',
                        '<li><input id="list10" name="list10" type="checkbox"><label for="list10"><p><a href="#">vloga za pridobitev pravice do plačila prispevkov za socialno zavarovanje</a></p></label></li>',
                        '<li><input id="list11" name="list11" type="checkbox"><label for="list11"><p><a href="#">obrazec za pridobitev pravice do plačila prispevkov</a></p></label></li>',
                    '</ul>',
                '</form>',
                '<p>Status samozaposlenega v kulturi se pridobi z vpisom v razvid samozaposlenih v kulturi. Ob vpisu v razvid je potrebno začeti plačevati prispevke za pokojninsko, invalidsko in obvezno zdravstveno zavarovanje.</p>',
                '<h3 class="nasveti">Navodila po korakih:</h3>',
                    '<form class="ac-custom ac-list" autocomplete="off">',
                        '<ul>',
                            '<li><input id="list12" name="list12" type="checkbox"><label for="list12"><p>Preberi me in klikni name</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list13" name="list13" type="checkbox"><label for="list13"><p>Natisni vse potrebne papirje (zgoraj)</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list14" name="list14" type="checkbox"><label for="list14"><p>Izpolni obrazce</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list15" name="list15" type="checkbox"><label for="list15"><p>Zapečati jih v kuverto in s priporočeno pošiljko odpošlji na:</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<p style="padding-left: 60px;">Ministrstvo za kulturo<br>Maistrova ulica 10<br>1000 Ljubljana</p>',
                        '</ul>',
                    '</form>',
                '</div>',
            '</div>'].join('\n')
    }, {
        'id': 2,
        'type': 'list',
        'content': [
            {
                'id': 3,
                'content': 'Civilna iniciativa', //TODO copy
                'subtitle': 'Bla bla bla la bla bla la bla bla la bla bla'
            },
            {
                'id': 4,
                'content': 'Društvo', //TODO copy
                'subtitle': 'Lalalalalala'
            },
            {
                'id': 5,
                'content': 'Zavod', //TODO copy
                'subtitle': 'Lalalalalala'
            }
        ]
    }, {
        'id': 3,
        'type': 'instructions',
        'content': [
            '<div class="htmlcontainer">',
                '<div class="visible-xs centermycontentvertically nazajcontainer"><div class="centermevertically nazaj bck">Nazaj</div></div>',
                '<p>Civilna oz. ljudska iniciativa je neposredna oblika sodelovanja državljanov pri odločanju na več ravneh: na ravni občine ali na ravni države. Iniciativa se zbere okrog zadeve, na katero želi opozoriti oz. spremembe, ki jo želi doseči. Če obstaja potreba po formalni organizaciji, se lahko iniciativa brez večjih težav preoblikuje v društvo.</p>',
                '<h3>Kakšne so prednosti in pomanjkljivosti civilne iniciative?</h3>',
                '<div class="tabs">',
                    '<div class="tab tab-prednosti open">prednosti</div>',
                    '<div class="tab tab-slabosti">slabosti</div>',
                '</div>',
                '<div class="content">',
                    '<div class="open">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list1" name="list1" type="checkbox"><label for="list1"><p>je popolnoma neformalna oblika združevanja</p></label></li>',
                                '<li><input id="list2" name="list2" type="checkbox"><label for="list2"><p>registracija ni potrebna</p></label></li>',
                                '<li><input id="list3" name="list3" type="checkbox"><label for="list3"><p>vse zadeve se uredijo z dogovorom med pripadniki iniciative</p></label></li>',
                                '<li><input id="list4" name="list4" type="checkbox"><label for="list4"><p>ni hierarhično urejena (razen, če se pripadniki odločijo drugače)</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                    '<div class="">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list5" name="list5" type="checkbox"><label for="list5"><p>iniciativa ne more pridobiti sredstev za svoje delovanje</p></label></li>',
                                '<li><input id="list6" name="list6" type="checkbox"><label for="list6"><p>ker je večinoma vezana na eno določeno zadevo, inicativa po spremembi hitro razpade</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                '</div>',
                '<h3 class="nasveti">Kako jo zaženem?</h3>',
                    '<form class="ac-custom ac-list" autocomplete="off">',
                        '<ul>',
                            '<li><input id="list7" name="list7" type="checkbox"><label for="list7"><p>Preberi me in klikni name</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list8" name="list8" type="checkbox"><label for="list8"><p>Zberi somišljenice/-ke (virtualno ali na kavi)</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list9" name="list9" type="checkbox"><label for="list9"><p>določite zadevo, na katero želite opozoriti ali spremembe, ki jih želite doseči</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list10" name="list10" type="checkbox"><label for="list10"><p>določite obseg, v katerem želite delovati (krajevna ali četrtna skupnost, občina, država, regija)</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list11" name="list11" type="checkbox"><label for="list11"><p>določite ključne odločevalce, na katere želite vplivati (kateri uradi, ministrstva in drugi odločevalci so pristojni za področje, na katerem želite doseči spremembo)</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list12" name="list12" type="checkbox"><label for="list12"><p>da bi izboljšali sodelovanje in participacijo med člani iniciative, lahko uporabite katero od metod, popisanih spodaj</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list13" name="list13" type="checkbox"><label for="list13"><p>določite načine, kako boste opozorili na svoje zahteve in predloge: prek javnega zborovanja, odprtega pisma, sestanka z odločevalci, delovanja na spletu, ...</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                        '</ul>',
                    '</form>',
                    '<h3 class="nasveti">Metoda za izboljšanje participacije med člani</h3>',
                    '<form class="ac-custom" autocomplete="off">',
                        '<ul>',
                            '<li><input id="list14" name="list14" type="checkbox"><label for="list14"><p><a href="http://www.participedia.net/en/browse/methods">Participedia</a></p></label></li>',
                            '<li><input id="list15" name="list15" type="checkbox"><label for="list15"><p><a href="http://www.nonformality.org/blog/wp-content/uploads/2006/12/mappingdialogue.pdf">Nonformality</a></p></label></li>',
                            '<li><input id="list16" name="list16" type="checkbox"><label for="list16"><p><a href="#">vloga za pridobitev pravice do plačila prispevkov za socialno zavarovanje</a></p></label></li>',
                            '<li><input id="list17" name="list17" type="checkbox"><label for="list17"><p><a href="http://www.bkpextranet.com/wulf/changehandbook.pdf">DEAD LINK</a></p></label></li>',
                        '</ul>',
                    '</form>',
                '</div>',
            '</div>'].join('\n')
    }, {
        'id': 4,
        'type': 'instructions',
        'content': [
            '<div class="htmlcontainer">',
                '<div class="visible-xs centermycontentvertically nazajcontainer"><div class="centermevertically nazaj bck">Nazaj</div></div>',
                '<p>Društvo je prostovoljno, samostojno in nepridobitno združenje, ki ga ustanovite zaradi uresničevanja skupnih interesov. Društvo si samo določi namen in cilje, dejavnost oziroma naloge ter način delovanja, odločitve o upravljanju društva pa sprejemajo članice oziroma člani društva.</p>',
                '<h3 class="nasveti">Kdaj ga ustanoviti?</h3>',
                '<form class="ac-custom" autocomplete="off">',
                    '<ul>',
                        '<li><input id="list1" name="list1" type="checkbox"><label for="list1"><p>ko želite delovati samostojno kot skupina</p></label></li>',
                        '<li><input id="list2" name="list2" type="checkbox"><label for="list2"><p>kadar želite delovati nepridobitno</p></label></li>',
                        '<li><input id="list3" name="list3" type="checkbox"><label for="list3"><p>ko želite pridobivati sredstva in jih nameniti za skupne cilje, katerim sledi društvo</p></label></li>',
                        '<li><input id="list4" name="list4" type="checkbox"><label for="list4"><p>kadar želite navzven nastopiti kot pravna oseba (na ta način lahko društvo razpolaga s svojim premoženjem, zaprosi za sredstva, vstopa v pogajanja …)</p></label></li>',
                        '<li><input id="list5" name="list5" type="checkbox"><label for="list5"><p>kadar želite svojemu smotru podeliti ime, pod katerim se boste predstavljali</p></label></li>',
                        '<li><input id="list6" name="list6" type="checkbox"><label for="list6"><p>kadar ne želite izpostaviti posameznikov, temveč namen, zaradi katerega delujete</p></label></li>',
                    '</ul>',
                '</form>',
                '<h3 class="nasveti">Kakšne so prednosti društva?</h3>',
                '<form class="ac-custom" autocomplete="off">',
                    '<ul>',
                        '<li><input id="list7" name="list7" type="checkbox"><label for="list7"><p>ni potrebno, da je pri društvu kdo zaposlen, vendar društvo lahko tudi zaposluje</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list8" name="list8" type="checkbox"><label for="list8"><p>članstvo je prostovoljno</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list9" name="list9" type="checkbox"><label for="list9"><p>članstvo ni pravica in se ne deduje</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list10" name="list10" type="checkbox"><label for="list10"><p>društvo odgovarja samo s svojim premoženjem</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                    '</ul>',
                '</form>',
                '<h3 class="nasveti">Kako ustanovimo društvo?</h3>',
                    '<form class="ac-custom ac-list" autocomplete="off">',
                        '<ul>',
                            '<li><input id="list20" name="list20" type="checkbox"><label for="list20"><p>preberite me in kliknite name</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>', // TODO list order
                            '<li><input id="list11" name="list11" type="checkbox"><label for="list11"><p>zberite se 3 polnoletne osebe</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list12" name="list12" type="checkbox"><label for="list12"><p>izberite zastopnika društva</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list13" name="list13" type="checkbox"><label for="list13"><p>izberite ime društva</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list14" name="list14" type="checkbox"><label for="list14"><p>določite sedež društva</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list19" name="list19" type="checkbox"><label for="list19"><p>zastopnik naj na (kateri koli) banki odpre tekoči račun društva</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>', // TODO list order
                            '<li><input id="list15" name="list15" type="checkbox"><label for="list15"><p>spišite in natisnite <a href="#">statut društva</a></p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list16" name="list16" type="checkbox"><label for="list16"><p>izpolnite in natisnite <a href="#">vlogo za registracijo društva</a></p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list17" name="list17" type="checkbox"><label for="list17"><p>pripravite in natisnite seznam z osebnimi podatki ustanoviteljev (ime, EMŠO, državljanstvo, naslov stalnega prebivališča) in njihovimi lastnoročnimi podpisi</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list18" name="list18" type="checkbox"><label for="list18"><p>iz statuta prepišite in natisnite podatek o (nepridobitnih) dejavnostih društva in predlog za glavno (nepridobitno) dejavnost</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                        '</ul>',
                    '</form>',
                '</div>',
            '</div>'].join('\n')
    }, {
        'id': 5,
        'type': 'instructions',
        'content': [
            '<div class="htmlcontainer">',
                '<div class="visible-xs centermycontentvertically nazajcontainer"><div class="centermevertically nazaj bck">Nazaj</div></div>',
                '<p>Zavod je ... manjka tekst</p>',
                '<h3 class="nasveti">Kdaj ga ustanoviti?</h3>',
                '<form class="ac-custom" autocomplete="off">',
                    '<ul>',
                        '<li><input id="list1" name="list1" type="checkbox"><label for="list1"><p>kadar se želite profesionalno ukvarjati s področji vzgoje in izobraževanja, znanosti, kulture, športa, zdravstva, socialnega varstva, otroškega varstva, invalidskega varstva, socialnega zavarovanja in drugih dejavnosti</p></label></li>',
                        '<li><input id="list2" name="list2" type="checkbox"><label for="list2"><p>ko vaš cilj ni pridobivanje dobička, temveč delo za razvoj določene dejavnosti</p></label></li>',
                        '<li><input id="list3" name="list3" type="checkbox"><label for="list3"><p>ko želite za dosego svojega cilja zaposliti druge strokovnjake s področja</p></label></li>',
                    '</ul>',
                '</form>',
                '<h3>Kakšne so prednosti in slabosti zavoda?</h3>',
                '<div class="tabs">',
                    '<div class="tab tab-prednosti open">prednosti</div>',
                    '<div class="tab tab-slabosti">slabosti</div>',
                '</div>',
                '<div class="content">',
                    '<div class="open">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list4" name="list4" type="checkbox"><label for="list4"><p>zavod deluje kot gospodarska družba na neprofitnem področju</p></label></li>',
                                '<li><input id="list5" name="list5" type="checkbox"><label for="list5"><p>omogoča profesionalno delovanje na področju, ki vas zanima</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                    '<div class="">',
                        '<form class="ac-custom" autocomplete="off">',
                            '<ul>',
                                '<li><input id="list6" name="list6" type="checkbox"><label for="list6"><p>sami boste morali določiti, koliko sredstev potrebujete za ustanovitev zavoda in začetek</p></label></li>',
                                '<li><input id="list7" name="list7" type="checkbox"><label for="list7"><p>organizacijska struktura zavoda je bolj zapletena od strukture društva (zavod mora imeti svet zavoda in strokovni svet)</p></label></li>',
                            '</ul>',
                        '</form>',
                    '</div>',
                '</div>',
                '<h3 class="nasveti">Kako ga ustanovimo?</h3>',
                    '<form class="ac-custom ac-list" autocomplete="off">',
                        '<ul>',
                            '<li><input id="list17" name="list17" type="checkbox"><label for="list17"><p>preberite me in klinite name</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>', // TODO list order
                            '<li><input id="list8" name="list8" type="checkbox"><label for="list8"><p>izberite direktorja zavoda</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list9" name="list9" type="checkbox"><label for="list9"><p>izberite ime zavoda</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list10" name="list10" type="checkbox"><label for="list10"><p>izberite sedež zavoda</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list11" name="list11" type="checkbox"><label for="list11"><p>spišite in natisnite <a href="#">akt o ustanovitvi zavoda</a></p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list12" name="list12" type="checkbox"><label for="list12"><p>izpolnite in natisnite <a href="#">sklep o imenovanju direktorja</a></p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list13" name="list13" type="checkbox"><label for="list13"><p>izpolnite in natisnite <a href="#">predlog za vpis zavoda v poslovni register</a></p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list14" name="list14" type="checkbox"><label for="list14"><p>najdite termin v delovnem času upravne enote, ko ste vsi ustanovitelji na voljo</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list15" name="list15" type="checkbox"><label for="list15"><p>ustanovitelji se zglasite na upravni enoti (ne pozabite na osebne dokumente) in overite akt o ustanovitvi zavoda</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                            '<li><input id="list16" name="list16" type="checkbox"><label for="list16"><p>vso dokumentacijo (akt o ustanovitvi, sklep o imenovanju direktorja in predlog za vpis zavoda v poslovni register) priporočeno pošljete na okrajno sodišče, kjer bo sedež zavoda</p><svg viewBox="0 0 300 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"></svg></label></li>',
                        '</ul>',
                    '</form>',
                '</div>',
            '</div>'].join('\n')
    }
];


a = {'id': 1, 'type': 'list', 'content': [{'id': 2, 'content': 'asd'}, {'id': 3, 'content': 'asd2'}]}
b = {'id': 4, 'type': 'instructions', 'content': '<div class="yomama">Yo mama so fat.</div>'}