apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eu-poslovi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - eu-poslovi.parlametar.hr
      secretName: eu-poslovi-tls
  rules:
    - host: eu-poslovi.parlametar.hr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eu-poslovi
                port:
                  number: 80
