apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vodic-pic-obnovljivi-viri
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.middlewares: |
      traefik-redirect-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ove.pic.si
      secretName: vodic-pic-obnovljivi-viri-tls
  rules:
    - host: ove.pic.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vodic-pic-obnovljivi-viri
                port:
                  number: 80
