apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: vodic-pic-obnovljivi-viri
    newName: rg.fr-par.scw.cloud/djnd/vodic-pic-obnovljivi-viri
    newTag: '66ad35aee4101a7973fb5e998126a1c6fb4b5637'
