apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: volitveni-vodic-referendum-jek2
    newName: rg.fr-par.scw.cloud/djnd/volitveni-vodic-referendum-jek2
    newTag: '5d62c9fb3a825c17f02d2d0fafe22fd35d656145'
