apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: volitveni-vodic-4xproti
    newName: rg.fr-par.scw.cloud/djnd/volitveni-vodic-4xproti
    newTag: '70a6d8cd7365aafbbaa3a29ec30a371ad073218f'
