apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: volitveni-vodic-4xproti
    newName: rg.fr-par.scw.cloud/djnd/volitveni-vodic-4xproti
    newTag: 'c423d565286a9b3e1a2507a668be44471d0277f7'
